[package]
name = "zipx-cli"
version = "0.1.0"
edition = "2021"

[dependencies]
zipx-core = { path = "../core" }
clap.workspace = true
tokio.workspace = true
tracing.workspace = true
tracing-subscriber.workspace = true
serde_json.workspace = true
